name: Deployment - Staging
# on: workflow_dispatch
on:
  push:
    branches:
      - develop

jobs:
  build-staging:
    runs-on: [self-hosted, staging]
    strategy:
      max-parallel: 4
    defaults:
      run:
        working-directory: /home/ubuntu/rest-api-dev/backend/action-runner/_work/framework-backend/framework-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create environment variable
        run: cp /home/ubuntu/rest-api-dev/backend/.env /home/ubuntu/rest-api-dev/backend/sendgrid_templates.json /home/ubuntu/rest-api-dev/backend/action-runner/_work/framework-backend/framework-backend

      - name: Creating Log Folder
        run: mkdir logs logs/db_query logs/debug logs/warning logs/error logs/info

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gunicorn
          python -m pip install -r requirements.txt

      - name: Build and collect static files
        run: python manage.py collectstatic --no-input

      - name: Migrate Database
        run: python manage.py migrate

      - name: Sync pgviews
        run: python manage.py sync_pgviews

      # - name: Run test case
      #   run: python manage.py test --verbosity=3 --exclude-tag=extended_slow --parallel

  deploy-staging:
    needs: build-staging
    runs-on: [self-hosted, staging]

    steps:
      - name: Restart server
        run: |
          sudo supervisorctl restart all
          sudo service nginx restart
