# Generated by Django 4.2.7 on 2023-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_is_file_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
